### ISSUE TITLE
error in viewdidload 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [HandcraftedMobile/HMScrollNavigationBar#1]
Do I need to import any modul or initiate anything ? because I have the same exact code but it shows an error 

<img width="947" alt="screen shot 2017-06-28 at 10 48 28 pm" src="https://user-images.githubusercontent.com/18103561/27657047-fbb8ce48-5c53-11e7-8deb-2682ba786883.png">

**Comment by piotr-sekara** [comment]
There is a mistake - you should have "self.navigationBarAnimator" instead "self.NavigationBarAnimator".

**Comment by AbdulazizAlmohsen** [comment]
still same issue. btw, thank you for the fast response 
<img width="724" alt="screen shot 2017-06-28 at 10 57 10 pm" src="https://user-images.githubusercontent.com/18103561/27657384-2c69bf4c-5c55-11e7-9f83-b2e77e6c9323.png">

**Comment by piotr-sekara** [comment]
I see one more thing - please import HMScrollNavigationBar, and then check :)

**Comment by AbdulazizAlmohsen** [comment]
problem solved. I think you need to mention this in the readme :)

**Comment by piotr-sekara** [comment]
Actually you are right, thanks ! :)

**Comment by AbdulazizAlmohsen** [comment]
does the UIView have to be inside the UITableview or outside ? I tried outside the table but when I run my project and scroll down the UIView is still up, doesn't fade. Do you mind adding a project example

**Comment by piotr-sekara** [comment]
I think that's because you have set delegate of tableview to your viewcontroller, but for now NavigationBarAnimator is a delegate of a UIScrollView in this UITableView. I will correct this issue, and I will add an example project ! :)

**Comment by AbdulazizAlmohsen** [comment]
can't wait to implement HMScrollNavigationBar in my project

**Comment by piotr-sekara** [comment]
I will correct it as fast as I can. Now is a night, so I tommorow I will do this :) Thank you for your attention !

**Comment by AbdulazizAlmohsen** [comment]
Nice!!! UIView now disappears while I scroll down but there is an issue with accessing table cell. When I click on a cell, I can access it ! that happens when I have dataSource before 
`        self.navigationBarAnimator.setup(scrollView : self.tableView , navBar : self.navBar)
`

**Comment by piotr-sekara** [comment]
I think I see where is the problem. Scroll works fine, but when you click on a cell, a delegate method is not invoked immediately. I will fix that.

**Comment by piotr-sekara** [comment]
Ahh, I just saw in example that I have used UITableView.didDeselectRowAt instead of UITableView.didSelectRowAt. When I changed it, everything is working fine. Can you describe your problem more? Maybe you had the same problem ?

**Comment by AbdulazizAlmohsen** [comment]
that's what I'm using 

` func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let meal =  shops[indexPath.row]
        guard shops.count > indexPath.row else {
            print("Index out of range")
            return
        }
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        var viewController = storyboard.instantiateViewController(withIdentifier: "viewControllerIdentifer") as! MealsDetailsController
        viewController.passedValue = meal.familiy_id
        self.present(viewController, animated: true , completion: nil)
        
    }
`

**Comment by piotr-sekara** [comment]
@AbdulazizAlmohsen I don't know what exactly you mean, what's the problem ? Everything should work fine with your code.

**Comment by AbdulazizAlmohsen** [comment]
but what's happening now is when I click on the cell , the cell is being highlted and selected but the vc is not presented. However when I have  tableView.delegate = self below your code I could access the cell and present the next vc but the UIView on top doesn't fade ( same old problem)

**Comment by piotr-sekara** [comment]
@AbdulazizAlmohsen I just have copied your code to Example project, and everything is working fine - vc is presented, and UIView is hiding.

![zrzut ekranu 2017-06-29 o 11 50 11](https://user-images.githubusercontent.com/19164218/27681953-2b39bdae-5cc1-11e7-97a2-33ec29dd0415.png)

**Comment by AbdulazizAlmohsen** [comment]
then I think the issue is the animation I'm using in the TableView. 
<img width="663" alt="screen shot 2017-06-29 at 12 59 40 pm" src="https://user-images.githubusercontent.com/18103561/27682337-d54163b6-5cca-11e7-92fe-e1deae441bb2.png">

**Comment by piotr-sekara** [comment]
@AbdulazizAlmohsen Nope, that's not the problem - still works fine in my example. I don't think if I can help without project.

**Comment by AbdulazizAlmohsen** [comment]
problem solved. Thank you very much.

**Comment by piotr-sekara** [comment]
@AbdulazizAlmohsen Could you tell what was the problem ? :)

**Comment by AbdulazizAlmohsen** [comment]
pod update just forgot to do it :)

**Comment by piotr-sekara** [comment]
Ahh ok, great that problem has been solved ! :) I will keep this issue open for a few days if you will have any questions :)
